name: NPM Publish

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (leave empty to use tag)"
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Extract version from tag
        id: get_version
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # 从推送的tag提取版本号（去掉v前缀）
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "Using version from tag: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          elif [[ -n "${{ github.event.inputs.version }}" ]]; then
            # 使用手动输入的版本号
            VERSION="${{ github.event.inputs.version }}"
            echo "Using manually provided version: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version specified"
            exit 1
          fi

      - name: Update package.json version
        run: |
          # 设置 package.json 中的版本号
          npm version ${{ steps.get_version.outputs.version }} --no-git-tag-version --allow-same-version

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
